// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBICJ_TR2W8-yfQ9TLiZP6kZBE1T5zhbOU',
    appId: '1:345297996485:web:66022810575a398f0cbeac',
    messagingSenderId: '345297996485',
    projectId: 'inkubator-300eb',
    authDomain: 'inkubator-300eb.firebaseapp.com',
    databaseURL: 'https://inkubator-300eb-default-rtdb.firebaseio.com',
    storageBucket: 'inkubator-300eb.appspot.com',
    measurementId: 'G-G1P8T4MD08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQbxMuTX7fMxE-R_uojAty9D7tQ8Zd7bI',
    appId: '1:345297996485:android:96f1cbfdea0e69aa0cbeac',
    messagingSenderId: '345297996485',
    projectId: 'inkubator-300eb',
    databaseURL: 'https://inkubator-300eb-default-rtdb.firebaseio.com',
    storageBucket: 'inkubator-300eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJAuL8VXlS1npzw80OJPUVuID6XqKT8xs',
    appId: '1:345297996485:ios:f092464e3d923e220cbeac',
    messagingSenderId: '345297996485',
    projectId: 'inkubator-300eb',
    databaseURL: 'https://inkubator-300eb-default-rtdb.firebaseio.com',
    storageBucket: 'inkubator-300eb.appspot.com',
    iosBundleId: 'com.example.incube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJAuL8VXlS1npzw80OJPUVuID6XqKT8xs',
    appId: '1:345297996485:ios:f092464e3d923e220cbeac',
    messagingSenderId: '345297996485',
    projectId: 'inkubator-300eb',
    databaseURL: 'https://inkubator-300eb-default-rtdb.firebaseio.com',
    storageBucket: 'inkubator-300eb.appspot.com',
    iosBundleId: 'com.example.incube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBICJ_TR2W8-yfQ9TLiZP6kZBE1T5zhbOU',
    appId: '1:345297996485:web:468e9d73402e31740cbeac',
    messagingSenderId: '345297996485',
    projectId: 'inkubator-300eb',
    authDomain: 'inkubator-300eb.firebaseapp.com',
    databaseURL: 'https://inkubator-300eb-default-rtdb.firebaseio.com',
    storageBucket: 'inkubator-300eb.appspot.com',
    measurementId: 'G-0KSLNKPRMM',
  );
}
